version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - ci
      - dependencies
    groups:
      ci-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      rust-development-tools:
        patterns:
          - "assert_cmd"
          - "criterion"
          - "insta"
          - "mockall"
          - "predicates"
          - "pretty_assertions"
          - "proptest"
          - "rstest"
          - "serial_test"
          - "snapbox"
          - "tempfile"
          - "tokio-test"
          - "trycmd"
          - "wiremock"
        update-types:
          - minor
          - patch
      rust-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
