name: reusable-ci

on:
  workflow_call:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: taiki-e/install-action@d426f49ab88a1c8303310abfe49d681889f497eb # main
        with:
          tool: cargo-llvm-cov@0.8.5
      - name: Format
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Test
        run: cargo llvm-cov --json --output-path target/coverage.json
      - name: Coverage Summary
        run: cargo llvm-cov report
      - name: Dogfood covgate
        run: cargo run -- check target/coverage.json --markdown-output "$GITHUB_STEP_SUMMARY"

  dependency-hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@d426f49ab88a1c8303310abfe49d681889f497eb # main
        with:
          tool: cargo-machete@0.9.1
      - name: Dependency hygiene
        run: cargo machete

  dependency-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@d426f49ab88a1c8303310abfe49d681889f497eb # main
        with:
          tool: cargo-deny@0.19.0
      - name: Dependency policy
        run: cargo deny check advisories licenses sources bans
